# Generated by Django 4.2 on 2023-05-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usernew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
        migrations.AlterField(
            model_name='usernew',
            name='password',
            field=models.TextField(max_length=128),
        ),
    ]
