# Generated by Django 4.2 on 2023-05-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_register_alter_usernew_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernew',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
