# Generated by Django 4.2 on 2023-05-23 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usernew_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept_rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_rol', models.CharField(max_length=15, verbose_name='tipo rol')),
                ('nombre_departamento', models.CharField(max_length=30, verbose_name='nombre departamento')),
            ],
        ),
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id_proveedores', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido_pro', models.CharField(max_length=30, verbose_name='apellido')),
                ('identificacion', models.CharField(max_length=15, verbose_name='identificacion')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha nacimiento')),
                ('profesion', models.CharField(max_length=50, verbose_name='profesion')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('ciudad_recidencia', models.CharField(max_length=50, verbose_name='Ciudada residencia')),
                ('telefono', models.CharField(max_length=10, verbose_name='telefono')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=15, verbose_name='identificacion')),
                ('nombre_user', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido_user', models.CharField(max_length=30, verbose_name='apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha nacimiento')),
                ('ciudad_recidencia', models.CharField(max_length=50, verbose_name='Ciudada residencia')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('telefono', models.CharField(max_length=10, verbose_name='telefono')),
                ('password', models.TextField(max_length=128, verbose_name='clave')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ser', models.CharField(max_length=30, verbose_name='nombre')),
                ('fecha_ser', models.DateField(verbose_name='fecha servicio')),
                ('precio_ser', models.IntegerField(max_length=2, verbose_name='precio')),
                ('calificacion', models.IntegerField(max_length=2, verbose_name='calificacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedores')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='pqr',
            fields=[
                ('id_pqr', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pqr', models.CharField(max_length=300, verbose_name='descripcion pqr')),
                ('solucion_pqr', models.CharField(max_length=300, verbose_name='solucion pqr')),
                ('fecha_pqr', models.DateField(verbose_name='fecha pqr')),
                ('fecha_solu_pqr', models.CharField(max_length=300, verbose_name='fecha solucion pqr')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id_empl', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empl', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido_empl', models.CharField(max_length=30, verbose_name='apellido')),
                ('identificacion_empl', models.CharField(max_length=15, verbose_name='identificacion')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='correo')),
                ('telefono', models.CharField(max_length=10, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion residencia')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha nacimiento')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dept_rol')),
            ],
        ),
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_doc', models.CharField(max_length=30, verbose_name='nombre')),
                ('documento', models.ImageField(upload_to='documentos')),
                ('tipo_doc', models.CharField(max_length=5, verbose_name='tipo de documento')),
                ('tamano', models.CharField(max_length=20, verbose_name='tamano de documento')),
                ('proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_soli',
            fields=[
                ('id_det_soli', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleados')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedores')),
            ],
        ),
    ]
