# Generated by Django 4.2 on 2023-05-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dept_rol_proveedores_usuarios_servicios_pqr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_usuarios',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='servicios',
            name='calificacion',
            field=models.IntegerField(verbose_name='calificacion'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='precio_ser',
            field=models.IntegerField(verbose_name='precio'),
        ),
    ]
