# Generated by Django 4.2 on 2023-05-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usuarios_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
