# Generated by Django 4.2 on 2023-05-24 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_usuarios_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
