# Generated by Django 4.2 on 2023-05-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usuarios_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.CharField(max_length=10, verbose_name='fecha nacimiento'),
        ),
    ]
