# Generated by Django 4.2 on 2023-05-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_usuarios_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='correo_electronico',
            field=models.CharField(max_length=50, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='correo',
            field=models.CharField(max_length=50, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='fecha_nacimiento',
            field=models.CharField(max_length=10, verbose_name='fecha nacimiento'),
        ),
    ]
