# Generated by Django 4.2 on 2023-05-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_empleados_correo_electronico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos',
            old_name='id_doc',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='id_proveedores',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='tamano',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='tipo_doc',
        ),
    ]
