# Generated by Django 4.2 on 2023-05-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_id_doc_documentos_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='password',
            field=models.TextField(default=2, max_length=128, verbose_name='clave'),
            preserve_default=False,
        ),
    ]
