# Generated by Django 4.2 on 2023-05-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_proveedores_last_login_proveedores_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos')),
            ],
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='documento',
        ),
        migrations.AlterField(
            model_name='documentos',
            name='nombre_doc',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='documentos',
            field=models.ManyToManyField(to='core.documento'),
        ),
    ]
