# Generated by Django 4.2 on 2023-05-26 00:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_documento_remove_documentos_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=core.models.get_documento_upload_path),
        ),
    ]
