# Generated by Django 4.2.4 on 2023-10-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_documentos_nombre_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='descripcion',
            field=models.CharField(max_length=300, null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='hora_ser',
            field=models.CharField(max_length=10, null=True, verbose_name='hora servicio'),
        ),
    ]
